export const SAVE_USER = "SAVE_USER";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const CHANGE_THEME = "CHANGE_THEME";
export const LOGOUT = "LOGOUT";

export const FETCH_POSTS_STARTED = "FETCH_POSTS_STARTED";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILUR = "FETCH_POSTS_FAILUR";

export const FETCH_FULL_POST_STARTED = "FETCH_FULL_POST_STARTED";
export const FETCH_FULL_POST_SUCCESS = "FETCH_FULL_POST_SUCCESS";
export const FETCH_FULL_POST_FAILUR = "FETCH_FULL_POST_FAILUR";

